[package]
name = "horologium-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
constellation-eridanus = { git = "https://git.starrytea.cc/Constellation-Project/Eridanus.git", rev = "20608d7225" }
chrono = "0.4.45"
anyhow = "1.0.103"
sanitize-filename = "0.6.0"
nanoid = "0.5.0"

[dependencies.uuid]
version = "1.24.0"
features = [
  "v7"
]
